title: "Example gallery"
menu:
  - name: "About"
    type: "page"
    url: "about"
  - name: "My first gallery"
    type: "folder"
    url: "first_gallery"
  - name: "Twitter"
    type: "external"
    url: "http://twitter.com"
