sudo: required
language: python
install:
  - sudo apt-get install graphicsmagick ffmpeg
  - pip install -r requirements.txt
  - python setup.py develop
python:
  - "2.7"
script:
  - cd example && prosopopee
notifications:
  irc: "chat.freenode.net#prosopopee"
